SELECT ma.Nachname & ", " & ma.Vorname AS Name, ma.Anstellungsart_ID, nv.Zeittyp_ID, 1 AS Monat, Sum(TageImMonat([vonDat],[bisDat],[Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr],1)) AS Tage FROM tbl_MA_NVerfuegZeiten AS nv INNER JOIN tbl_MA_Mitarbeiterstamm AS ma ON nv.MA_ID = ma.ID WHERE (Year([vonDat]) = [Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr] OR Year([bisDat]) = [Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr]) AND ma.Anstellungsart_ID = [Formulare]![frm_N_MA_Monatsuebersicht]![cboAnstellungsart] GROUP BY ma.Nachname & ", " & ma.Vorname, ma.Anstellungsart_ID, nv.Zeittyp_ID
UNION ALL
SELECT ma.Nachname & ", " & ma.Vorname AS Name, ma.Anstellungsart_ID, nv.Zeittyp_ID, 2 AS Monat, Sum(TageImMonat([vonDat],[bisDat],[Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr],2)) AS Tage FROM tbl_MA_NVerfuegZeiten AS nv INNER JOIN tbl_MA_Mitarbeiterstamm AS ma ON nv.MA_ID = ma.ID WHERE (Year([vonDat]) = [Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr] OR Year([bisDat]) = [Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr]) AND ma.Anstellungsart_ID = [Formulare]![frm_N_MA_Monatsuebersicht]![cboAnstellungsart] GROUP BY ma.Nachname & ", " & ma.Vorname, ma.Anstellungsart_ID, nv.Zeittyp_ID
UNION ALL
SELECT ma.Nachname & ", " & ma.Vorname AS Name, ma.Anstellungsart_ID, nv.Zeittyp_ID, 3 AS Monat, Sum(TageImMonat([vonDat],[bisDat],[Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr],3)) AS Tage FROM tbl_MA_NVerfuegZeiten AS nv INNER JOIN tbl_MA_Mitarbeiterstamm AS ma ON nv.MA_ID = ma.ID WHERE (Year([vonDat]) = [Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr] OR Year([bisDat]) = [Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr]) AND ma.Anstellungsart_ID = [Formulare]![frm_N_MA_Monatsuebersicht]![cboAnstellungsart] GROUP BY ma.Nachname & ", " & ma.Vorname, ma.Anstellungsart_ID, nv.Zeittyp_ID
UNION ALL
SELECT ma.Nachname & ", " & ma.Vorname AS Name, ma.Anstellungsart_ID, nv.Zeittyp_ID, 4 AS Monat, Sum(TageImMonat([vonDat],[bisDat],[Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr],4)) AS Tage FROM tbl_MA_NVerfuegZeiten AS nv INNER JOIN tbl_MA_Mitarbeiterstamm AS ma ON nv.MA_ID = ma.ID WHERE (Year([vonDat]) = [Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr] OR Year([bisDat]) = [Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr]) AND ma.Anstellungsart_ID = [Formulare]![frm_N_MA_Monatsuebersicht]![cboAnstellungsart] GROUP BY ma.Nachname & ", " & ma.Vorname, ma.Anstellungsart_ID, nv.Zeittyp_ID
UNION ALL
SELECT ma.Nachname & ", " & ma.Vorname AS Name, ma.Anstellungsart_ID, nv.Zeittyp_ID, 5 AS Monat, Sum(TageImMonat([vonDat],[bisDat],[Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr],5)) AS Tage FROM tbl_MA_NVerfuegZeiten AS nv INNER JOIN tbl_MA_Mitarbeiterstamm AS ma ON nv.MA_ID = ma.ID WHERE (Year([vonDat]) = [Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr] OR Year([bisDat]) = [Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr]) AND ma.Anstellungsart_ID = [Formulare]![frm_N_MA_Monatsuebersicht]![cboAnstellungsart] GROUP BY ma.Nachname & ", " & ma.Vorname, ma.Anstellungsart_ID, nv.Zeittyp_ID
UNION ALL
SELECT ma.Nachname & ", " & ma.Vorname AS Name, ma.Anstellungsart_ID, nv.Zeittyp_ID, 6 AS Monat, Sum(TageImMonat([vonDat],[bisDat],[Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr],6)) AS Tage FROM tbl_MA_NVerfuegZeiten AS nv INNER JOIN tbl_MA_Mitarbeiterstamm AS ma ON nv.MA_ID = ma.ID WHERE (Year([vonDat]) = [Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr] OR Year([bisDat]) = [Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr]) AND ma.Anstellungsart_ID = [Formulare]![frm_N_MA_Monatsuebersicht]![cboAnstellungsart] GROUP BY ma.Nachname & ", " & ma.Vorname, ma.Anstellungsart_ID, nv.Zeittyp_ID
UNION ALL
SELECT ma.Nachname & ", " & ma.Vorname AS Name, ma.Anstellungsart_ID, nv.Zeittyp_ID, 7 AS Monat, Sum(TageImMonat([vonDat],[bisDat],[Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr],7)) AS Tage FROM tbl_MA_NVerfuegZeiten AS nv INNER JOIN tbl_MA_Mitarbeiterstamm AS ma ON nv.MA_ID = ma.ID WHERE (Year([vonDat]) = [Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr] OR Year([bisDat]) = [Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr]) AND ma.Anstellungsart_ID = [Formulare]![frm_N_MA_Monatsuebersicht]![cboAnstellungsart] GROUP BY ma.Nachname & ", " & ma.Vorname, ma.Anstellungsart_ID, nv.Zeittyp_ID
UNION ALL
SELECT ma.Nachname & ", " & ma.Vorname AS Name, ma.Anstellungsart_ID, nv.Zeittyp_ID, 8 AS Monat, Sum(TageImMonat([vonDat],[bisDat],[Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr],8)) AS Tage FROM tbl_MA_NVerfuegZeiten AS nv INNER JOIN tbl_MA_Mitarbeiterstamm AS ma ON nv.MA_ID = ma.ID WHERE (Year([vonDat]) = [Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr] OR Year([bisDat]) = [Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr]) AND ma.Anstellungsart_ID = [Formulare]![frm_N_MA_Monatsuebersicht]![cboAnstellungsart] GROUP BY ma.Nachname & ", " & ma.Vorname, ma.Anstellungsart_ID, nv.Zeittyp_ID
UNION ALL
SELECT ma.Nachname & ", " & ma.Vorname AS Name, ma.Anstellungsart_ID, nv.Zeittyp_ID, 9 AS Monat, Sum(TageImMonat([vonDat],[bisDat],[Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr],9)) AS Tage FROM tbl_MA_NVerfuegZeiten AS nv INNER JOIN tbl_MA_Mitarbeiterstamm AS ma ON nv.MA_ID = ma.ID WHERE (Year([vonDat]) = [Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr] OR Year([bisDat]) = [Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr]) AND ma.Anstellungsart_ID = [Formulare]![frm_N_MA_Monatsuebersicht]![cboAnstellungsart] GROUP BY ma.Nachname & ", " & ma.Vorname, ma.Anstellungsart_ID, nv.Zeittyp_ID
UNION ALL
SELECT ma.Nachname & ", " & ma.Vorname AS Name, ma.Anstellungsart_ID, nv.Zeittyp_ID, 10 AS Monat, Sum(TageImMonat([vonDat],[bisDat],[Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr],10)) AS Tage FROM tbl_MA_NVerfuegZeiten AS nv INNER JOIN tbl_MA_Mitarbeiterstamm AS ma ON nv.MA_ID = ma.ID WHERE (Year([vonDat]) = [Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr] OR Year([bisDat]) = [Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr]) AND ma.Anstellungsart_ID = [Formulare]![frm_N_MA_Monatsuebersicht]![cboAnstellungsart] GROUP BY ma.Nachname & ", " & ma.Vorname, ma.Anstellungsart_ID, nv.Zeittyp_ID
UNION ALL
SELECT ma.Nachname & ", " & ma.Vorname AS Name, ma.Anstellungsart_ID, nv.Zeittyp_ID, 11 AS Monat, Sum(TageImMonat([vonDat],[bisDat],[Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr],11)) AS Tage FROM tbl_MA_NVerfuegZeiten AS nv INNER JOIN tbl_MA_Mitarbeiterstamm AS ma ON nv.MA_ID = ma.ID WHERE (Year([vonDat]) = [Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr] OR Year([bisDat]) = [Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr]) AND ma.Anstellungsart_ID = [Formulare]![frm_N_MA_Monatsuebersicht]![cboAnstellungsart] GROUP BY ma.Nachname & ", " & ma.Vorname, ma.Anstellungsart_ID, nv.Zeittyp_ID
UNION ALL SELECT ma.Nachname & ", " & ma.Vorname AS Name, ma.Anstellungsart_ID, nv.Zeittyp_ID, 12 AS Monat, Sum(TageImMonat([vonDat],[bisDat],[Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr],12)) AS Tage FROM tbl_MA_NVerfuegZeiten AS nv INNER JOIN tbl_MA_Mitarbeiterstamm AS ma ON nv.MA_ID = ma.ID WHERE (Year([vonDat]) = [Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr] OR Year([bisDat]) = [Formulare]![frm_N_MA_Monatsuebersicht]![cboJahr]) AND ma.Anstellungsart_ID = [Formulare]![frm_N_MA_Monatsuebersicht]![cboAnstellungsart] GROUP BY ma.Nachname & ", " & ma.Vorname, ma.Anstellungsart_ID, nv.Zeittyp_ID;

